### ISSUE TITLE
display-results tasks yields error: `max_measurement_number: unbound variable`

### ISSUE THREAD

**Issue by marians** [green-coding-solutions/eco-ci-energy-estimation#43]
I just added the two steps shown in the example in https://github.com/marketplace/actions/eco-ci-energy-estimation to a workflow and executed it. As a result, I got this error in the "Show energy results" step 

```
Running a measurement to have at least one result to display.
|Label|🖥 avg. CPU utilization [%]|🔋 Total Energy [Joules]|🔌 avg. Power [Watts]|Duration [Seconds]|
|---|---|---|---|---|
|Total Run|2.38538|360.733|1.97122|184|
/home/runner/work/_actions/green-coding-berlin/eco-ci-energy-estimation/v2/scripts/display_results.sh: line 98: max_measurement_number: unbound variable
Error: Process completed with exit code 1.
```

The workflow snippet:

```yaml
      - name: Show energy results
        uses: green-coding-berlin/eco-ci-energy-estimation@v2
        with:
          task: display-results
```
